-- drop all business tables
DROP TABLE  TEST_BATCH_SEC_CNVT ;

-- create all business tables

CREATE TABLE TEST_BATCH_SEC_CNVT  (
	SEC_CNVT_SEQ_NUM NUMBER,
	TRANSACTIONCODE VARCHAR2(32) ,
	TRANSACTIONDATETIME TIMESTAMP ,
	CUSTOMERPARTNUMBER VARCHAR2(32) ,
	INTERNALPLANTCODE VARCHAR2(32) ,
	ZEROQUANTITYINDICATOR VARCHAR2(32) ,
	BASEUOM VARCHAR2(32)
) ;